platform :ios, '13.0'
use_frameworks!

target 'App' do
  capacitor_path = '../node_modules/@capacitor/ios'
  pod '@capacitor/cli', :path => capacitor_path
  pod '@capacitor/core', :path => capacitor_path
  pod '@capacitor/ios', :path => capacitor_path
  pod '@capacitor/filesystem', :path => '../node_modules/@capacitor/filesystem'
end
